#
# Go lang debian container
#
# To build docker build --rm -t golang .
# To Run docker run -it --rm --name go1 golang
#

FROM golang

# Create the working directories

# Mount the volumes

WORKDIR /go/src/

CMD ["bash"]

